name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Set this to the branch containing your book source

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main  # Set this to the branch containing your book source

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Build Jupyter Book
      run: |
        jupyter-book build .

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
